Endpoint.Site/Views/Shared/Components/ModalLogin/ModalLoginViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Endpoint.Site.Views.Shared.Components.Login
{
    public class ModalLoginViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("Index");
        }
    }
}

Endpoint.Site/Views/Shared/Components/TopRightUserPanel/TopRightUserPanelViewComponent.cs
using Endpoint.Site.Utilities;
using galaxypremiere.Application.Interfaces.FacadePattern;
using galaxypremiere.Common.Constants;
using galaxypremiere.Domain.Entities.Users;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Endpoint.Site.Views.Shared.Components;

public class TopRightUserPanelViewComponent : ViewComponent
{    
    public IViewComponentResult Invoke()
    {     
        return View("Index");
    }
}

Endpoint.Site/Views/Shared/Components/UserAccountNavigation/UserAccountNavigationViewComponent.cs
using Endpoint.Site.Utilities;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Endpoint.Site.Views.Shared.Components.UserAccountNavigation
{
    public class UserAccountNavigationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("Index");
        }
    }
}

Endpoint.Site/Views/Shared/Components/UserLeftSliderMenu/UserLeftSliderMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Endpoint.Site.Views.Shared.Components.UserLeftSliderMenu
{
    public class UserLeftSliderMenuViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("Index");
        }
    }
}

Endpoint.Site/Views/Shared/Components/UserPhotosNavigation/UserPhotosNavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Endpoint.Site.Views.Shared.Components.UserPhotosNavigation
{
    public class UserPhotosNavigationViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("Index");
        }
    }
}

Endpoint.Site/Views/Shared/Components/UserProfileNavigation/UserProfileNavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Endpoint.Site.Views.Shared.Components.UserProfileNavigation
{
    public class UserProfileNavigationViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("Index");
        }
    }
}

Endpoint.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Submit Your Films & Scripts Freely | Galaxy Premiere</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/sitetemplate/mainpage/assets/img/favicon.png" rel="icon">
    <link href="~/sitetemplate/mainpage/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/sitetemplate/mainpage/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/sitetemplate/mainpage/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/sitetemplate/mainpage/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/sitetemplate/mainpage/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/sitetemplate/mainpage/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/sitetemplate/mainpage/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="~/sitetemplate/mainpage/assets/css/style.css" rel="stylesheet">
    <!-- SweetAlert -->
    <link href="~/sweetalert/sweetalert2.min.css" rel="stylesheet" />
</head>

<body>
    <!-- ======= Mobile nav toggle button ======= -->
    <!-- <button type="button" class="mobile-nav-toggle d-xl-none"><i class="bi bi-list mobile-nav-toggle"></i></button> -->
    <i class="bi bi-list mobile-nav-toggle d-lg-none"></i>
    <!-- ======= Header ======= -->
    <header id="header" class="d-flex flex-column justify-content-center">
        <nav id="navbar" class="navbar nav-menu">
            <ul>
                <li><a onclick="showLoginModal()" class="nav-link scrollto"><i class="bx bx-user"></i> <span>Sign-In</span></a></li>
                <li><a href="#festival" class="nav-link scrollto"><i class="bx bx-file-blank"></i> <span>Browse Festivals</span></a></li>
                <li><a href="#galaxypremiere" class="nav-link scrollto"><i class="bx bx-book-content"></i> <span>Who Are We?</span></a></li>
                @*        <li><a href="#services" class="nav-link scrollto"><i class="bx bx-server"></i> <span>Services</span></a></li>
                <li><a href="#contact" class="nav-link scrollto"><i class="bx bx-envelope"></i> <span>Contact</span></a></li>*@
            </ul>
        </nav><!-- .nav-menu -->

    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->

    <section id="hero" class="d-flex flex-column justify-content-center">

        <div class="container" data-aos="zoom-in" data-aos-delay="100">

            <div class="ContentAstronaut">
                <img class="astronaut" src="~/sitetemplate/mainpage/assets/img/astronaut.png" width="50%" />
            </div>


            <h1>Submit Freely!</h1>
            <p>Are you <span class="typed" data-typed-items="a Filmmaker?, an International Distributor?, a Festival Coordinator?"></span></p>
            <div class="social-links">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
        </div>
    </section><!-- End Hero -->
    @RenderBody()
    <!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="container">
            <h3>GALAXY PREMIERE</h3>
            <p>easily submitted films and scripts, managed films, and held international film festivals</p>
            <div class="social-links">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
            <div class="copyright">
                &copy; Galaxy Premiere Co.
            </div>
            <div class="credits">
                Developed by <a href="https://eghbaldar.ir/">AE STUDIOS</a>
            </div>
        </div>
    </footer><!-- End Footer -->
    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <!-- Vendor JS Files -->
    <script src="~/sitetemplate/mainpage/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/sitetemplate/mainpage/assets/vendor/aos/aos.js"></script>
    <script src="~/sitetemplate/mainpage/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/sitetemplate/mainpage/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/sitetemplate/mainpage/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/sitetemplate/mainpage/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/sitetemplate/mainpage/assets/vendor/typed.js/typed.umd.js"></script>
    <script src="~/sitetemplate/mainpage/assets/vendor/waypoints/noframework.waypoints.js"></script>
    <script src="~/sitetemplate/mainpage/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/sitetemplate/mainpage/assets/js/main.js"></script>
    <!-- SweetAlert -->
    <script src="~/sweetalert/sweetalert2.all.min.js"></script>
    <script src="~/sweetalert/sweetalert2.min.js"></script>
    <!-- jQuery Modal -->
    <!-- End -->
    <!-- Modal Component -->
    @await Component.InvokeAsync("ModalLogin")
    <!-- End Modal -->
    <script>
        // run when page loads
        $(document).ready(function () {
            // when users back to the fist page because unauthenticated
            const params = new URLSearchParams(window.location.search);
            if (params.get('login') != null) showLoginModal();
            // end
        });
    </script>
</body>

</html>

Endpoint.Site/Views/Shared/_LayoutInnerPages.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>@ViewData["PageTitle"]</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- site icon -->
    <link rel="icon" href="~/SiteTemplate/innerpages/innerpages/images/fevicon.png" type="image/png" />
    <!-- fontawesome icons -->
    <link href="~/sitetemplate/innerpages/fonts/fontawesome6/css/fontawesome.min.css" rel="stylesheet" />
    <link href="~/sitetemplate/innerpages/fonts/fontawesome6/css/brands.min.css" rel="stylesheet" />
    <link href="~/sitetemplate/innerpages/fonts/fontawesome6/css/solid.min.css" rel="stylesheet" />
    <!-- bootstrap css -->
    <link rel="stylesheet" href="~/SiteTemplate/innerpages/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" />*@
    <!-- site css -->
    <link rel="stylesheet" href="~/SiteTemplate/innerpages/css/style.css" />
    <link rel="stylesheet" href="~/SiteTemplate/innerpages/css/animate.css" />
    <link rel="stylesheet" href="~/SiteTemplate/innerpages/css/flaticon.css" />
    <link rel="stylesheet" href="~/SiteTemplate/innerpages/css/font-awesome.min.css" />
    <!-- responsive css -->
    <link rel="stylesheet" href="~/SiteTemplate/innerpages/css/responsive.css" />
    <!-- color css -->
    <link rel="stylesheet" href="~/SiteTemplate/innerpages/css/colors.css" />
    <!-- select bootstrap -->
    <link rel="stylesheet" href="~/SiteTemplate/innerpages/css/bootstrap-select.css" />
    <!-- scrollbar css -->
    <link rel="stylesheet" href="~/SiteTemplate/innerpages/css/perfect-scrollbar.css" />
    <!-- custom css -->
    <link rel="stylesheet" href="~/SiteTemplate/innerpages/css/custom.css" />
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="~/lib/kingfuncs/general/general.css" rel="stylesheet" />
    @RenderSection("Styles", required:false)
</head>
<body class="dashboard dashboard_1">
    <div class="full_container">
        <div class="inner_container">
            <!-- Sidebar  -->
            @await Component.InvokeAsync("UserLeftSliderMenu")
            <!-- end sidebar -->
            <!-- right content -->
            <div id="content">
                <!-- topbar -->
                <div class="topbar">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <div class="full">
                            <button type="button" id="sidebarCollapse" class="sidebar_toggle"><i class="fa fa-bars"></i></button>
                            <div class="logo_section">
                                <a href="index.html"><img class="img-responsive" src="~/SiteTemplate/innerpages/images/logo/logo.png" alt="#" /></a>
                            </div>
                            <div class="right_topbar">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    @await Component.InvokeAsync("TopRightUserPanel") <i class="mdi mdi-chevron-down"></i>
                                }
                            </div>
                        </div>
                    </nav>
                </div>
                <!-- end topbar -->
                <!-- dashboard inner -->
                @RenderBody()
                <!-- end dashboard inner -->
            </div>
        </div>
    </div>
    <!-- Modal Component -->
    @await Component.InvokeAsync("ModalLogin")
    <!-- End Modal -->
    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery-3.7.1.min.js"></script>
    <script src="~/SiteTemplate/innerpages/js/popper.min.js"></script>
    <script src="~/SiteTemplate/innerpages/js/bootstrap.min.js"></script>
    <!-- wow animation -->
    <script src="~/SiteTemplate/innerpages/js/animate.js"></script>
    <!-- select country -->
    <script src="~/SiteTemplate/innerpages/js/bootstrap-select.js"></script>
    <!-- owl carousel -->
    <script src="~/SiteTemplate/innerpages/js/owl.carousel.js"></script>
    <!-- chart js -->
    <script src="~/SiteTemplate/innerpages/js/Chart.min.js"></script>
    <script src="~/SiteTemplate/innerpages/js/Chart.bundle.min.js"></script>
    <script src="~/SiteTemplate/innerpages/js/utils.js"></script>
    <script src="~/SiteTemplate/innerpages/js/analyser.js"></script>
    <!-- nice scrollbar -->
    <script src="~/SiteTemplate/innerpages/js/perfect-scrollbar.min.js"></script>
    <script>
        var ps = new PerfectScrollbar('#sidebar');
    </script>
    <!-- custom js -->
    <script src="~/SiteTemplate/innerpages/js/custom.js"></script>
    <script src="~/SiteTemplate/innerpages/js/chart_custom_style1.js"></script>
    <!-- Sweat Alert -->
    <script src="~/sweetalert/sweetalert2.all.min.js"></script>
    <script src="~/sweetalert/sweetalert2.min.js"></script>
    <link href="~/sweetalert/sweetalert2.min.css" rel="stylesheet" />
    <!-- These validation libraries need to be included for unobtrusive validation -->
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <!-- WaitME -->
    <link href="~/waitme/waitme.css" rel="stylesheet" />
    <script src="~/waitme/waitmeking.js"></script>
    <script src="~/waitme/waitme.min.js"></script>
    <!-- King General -->
    <script src="~/lib/kingfuncs/general/general.js"></script>
    <!-- Render Sections -->
    @RenderSection("Scripts",required:false)
</body>
</html>