Endpoint.Site/Models/Users/GetInformation/ModelGetInformation.cs
using galaxypremiere.Application.Services.Countries.Queries.GetCountries;
using galaxypremiere.Application.Services.Languages.Queries.GetLanguages;
using galaxypremiere.Application.Services.UsersInformation.Queries.GetUsersInformation;
using galaxypremiere.Application.Services.UsersInformation.Queries.GetUsersInformationContact;

namespace Endpoint.Site.Models.Users.GetInformation
{
    public class ModelGetInformation
    {
        public GetUsersInformationServiceDto getUsersInformationServiceDto { get; set; }
        public GetUsersInformationContactServiceDto getUsersInformationContactServiceDto { get; set; }
        public ResultGetCountriesServiceDto resultGetCountriesServiceDto { get; set; }
        public ResultGetLanguagesServiceDto resultGetLanguagesServiceDto { get; set; }
    }
}

Endpoint.Site/Models/Users/GetPhoto/ModelGetPhoto.cs
using galaxypremiere.Application.Services.UsersPhotos.Queries.GetUsersPhotoAlbum;
using galaxypremiere.Application.Services.UsersPhotos.Queries.GetUsersPhotoPhotos;

namespace Endpoint.Site.Models.Users.GetPhoto
{
    public class ModelGetPhoto
    {
        public ResultGetUsersPhotoAlbumServiceDto ResultGetUsersPhotoAlbumServiceDto { get; set; }
        public ResultGetUsersPhotoPhotosServiceDto ResultGetUsersPhotoPhotosServiceDto { get; set; }
    }
}

Endpoint.Site/Models/Users/GetProfile/ModelGetProfile.cs
using galaxypremiere.Application.Services.Countries.Queries.GetCountries;
using galaxypremiere.Application.Services.UsersProfile.Queries.GetUserProfileAttachments;
using galaxypremiere.Application.Services.UsersProfile.Queries.GetUserProfileCompanies;
using galaxypremiere.Application.Services.UsersProfile.Queries.GetUserProfileEducations;
using galaxypremiere.Application.Services.UsersProfile.Queries.GetUserProfileFavoriteMovies;
using galaxypremiere.Application.Services.UsersProfile.Queries.GetUserProfileLinks;
using galaxypremiere.Application.Services.UsersProfile.Queries.GetUserProfileNews;

namespace Endpoint.Site.Models.Users.GetProfile
{
    public class ModelGetProfile
    {
        public ResultGetUserProfileEducationsServiceDto ResultGetUserProfileEducationsServiceDto { get; set; }
        public ResultGetUserProfileFavoriteMoviesServiceDto ResultGetUserProfileFavoriteMoviesServiceDto { get; set; }
        public ResultGetCountriesServiceDto resultGetCountriesServiceDto { get; set; }
        public ResultGetUserProfileCompaniesServiceDto ResultGetUserProfileCompaniesServiceDto { get; set; }
        public ResultGetUserProfileNewsServiceDto ResultGetUserProfileNewsServiceDto{ get; set; }
        public ResultGetUserProfileLinksServiceDto ResultGetUserProfileLinksServiceDto{ get; set; }
        public ResultGetUserProfileAttachmentsServiceDto ResultGetUserProfileAttachmentsServiceDto { get; set; }
    }
}

Endpoint.Site/Areas/Admin/Controllers/UserController.cs
using AutoMapper;
using galaxypremiere.Application.Interfaces.FacadePattern;
using galaxypremiere.Application.Services.UserLoginLog.Queries.GetUsersLoginLogs;
using galaxypremiere.Application.Services.Users.Commands.ActivateUser;
using galaxypremiere.Application.Services.Users.Commands.DeleteUser;
using galaxypremiere.Application.Services.Users.Commands.PostUser;
using galaxypremiere.Application.Services.Users.Commands.UpdateUser;
using galaxypremiere.Common.Constants;
using galaxypremiere.Domain.Entities.Users;
using galaxypremiere.Infrastructure.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Endpoint.Site.Areas.Admin.Controllers
{
    [ModelStateAttribute]
    [Area("Admin")]
    [Authorize(RoleConstants.King)]
    public class UserController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IRolesFacade _rolesFacade;
        private readonly IUserFacade _userFacade;
        private readonly IUserLoginLogFacade _userLoginLogFacade;
        public UserController(
            IRolesFacade rolesFacade,
            IUserFacade userFacade,
            IMapper mapper,
            IUserLoginLogFacade userLoginLogFacade
            )
        {
            _rolesFacade = rolesFacade;
            _userFacade = userFacade;
            _mapper = mapper;
            _userLoginLogFacade = userLoginLogFacade;
        }

        [HttpGet]
        public IActionResult Create()
        {
            var roles = new SelectList(_rolesFacade.GetRolesService.Execute(), "Id", "Name");
            ViewBag.Roles = roles;
            return View();
        }
        [HttpPost]
        public IActionResult Create(RequestPostUserServiceDto req)
        {
            return Json(_userFacade.PostUserService.Execute(_mapper.Map<RequestPostUserServiceDto>(req)));
        }
        [HttpGet]
        public IActionResult Index(int p)
        {
            var roles = new SelectList(_rolesFacade.GetRolesService.Execute(), "Id", "Name");
            ViewBag.Roles = roles;
            return View(_userFacade.GetUsersService.Execute(new galaxypremiere.Application.Services.Users.Queries.GetUsers.RequestGetUserServiceDto
            {
                CurrentPage = p,
            }));
        }
        [HttpPost]
        public IActionResult Update(RequestUpdateUserServiceDto req)
        {
            return Json(_userFacade.UpdateUserService.Execute(_mapper.Map<RequestUpdateUserServiceDto>(req)));
        }
        [HttpPost]
        public IActionResult Delete(RequestDeleteUserServiceDto req)
        {
            return Json(_userFacade.DeleteUserService.Execute(req));
        }
        [HttpPost]
        public IActionResult Activate(RequestActiviateUserServiceDto req)
        {
            return Json(_userFacade.ActiviateUserService.Execute(req));
        }
        [HttpGet]
        public IActionResult LoginLogs(RequestGetUsersLoginLogsServiceDto req, int p)
        {
            string userId = RouteData.Values["id"].ToString();
            return View(_userLoginLogFacade.GetUsersLoginLogsService.Execute(new RequestGetUsersLoginLogsServiceDto
            {
                UsersId = int.Parse(userId),
                Page = p,
            }));
        }
        [HttpGet]
        public IActionResult Information()
        {
            return View();
        }
    }
}

Endpoint.Site/Controllers/ProfileController.cs
using Endpoint.Site.Models.Porfile.GetInformationByUsername;
using galaxypremiere.Application.Interfaces.FacadePattern;
using galaxypremiere.Application.Services.UsersInformation.Queries.GetUsersInformationByUsername;
using galaxypremiere.Application.Services.UsersInformation.Queries.GetUsersInformationAboutByUsername;
using Microsoft.AspNetCore.Mvc;
using galaxypremiere.Application.Services.UsersInformation.Queries.GetUsersInformationPositions;
using galaxypremiere.Application.Services.UsersInformation.Queries.GetUsersInformationContactByUsername;
using galaxypremiere.Application.Services.UsersInformation.Queries.GetUsersInformationPhotosByUsername;
using galaxypremiere.Application.Services.UsersPhotos.Commands.PostUsersPhotoComment;
using Endpoint.Site.Utilities;
using System.Security.Claims;
using galaxypremiere.Common.Constants;
using galaxypremiere.Application.Services.UsersPhotos.Commands.DeleteUsersPhotoComment;
using galaxypremiere.Application.Services.UsersPhotos.Commands.PostUsersPhotoIncreaseVisitorCounter;
using galaxypremiere.Application.Services.Likes.Commands.PostLike;
using galaxypremiere.Application.Services.UsersInformation.Queries.GetUsersInformationUsernameByUserId;
using galaxypremiere.Application.Services.UsersPosts.Commands.PostUsersPost;
using galaxypremiere.Application.Services.UsersPosts.Queries.GetUsersPosts;
using galaxypremiere.Application.Services.Comments.Commands.PostComment;
using galaxypremiere.Application.Services.Comments.Commands.DeleteComment;
using galaxypremiere.Application.Services.Comments.Queries.GetCommentsBySectionId;
using galaxypremiere.Application.Services.UsersPosts.Commands.PostUsersPostArchive;
using galaxypremiere.Application.Services.UsersPosts.Commands.DeleteUsersPost;
using galaxypremiere.Domain.Entities.Users;

namespace Endpoint.Site.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IUserInformationFacade _userInformationFacade;
        private readonly IUserPhotoFacade _userPhoto;
        private readonly ILikesFacade _ikesFacade;
        private readonly IUsersPostFacade _usersPost;
        private readonly IUsersPostsPhotosFacade _usersPostsPhotosFacade;
        private readonly ICommentsFacade _commentsFacade;
        public ProfileController(IUserInformationFacade userInformationFacade,
            IUserPhotoFacade userPhotoFacade,
            ILikesFacade ikesFacade,
            IUsersPostFacade usersPost,
            IUsersPostsPhotosFacade usersPostsPhotosFacade,
            ICommentsFacade commentsFacade)
        {
            _userInformationFacade = userInformationFacade;
            _userPhoto = userPhotoFacade;
            _ikesFacade = ikesFacade;
            _usersPost = usersPost;
            _usersPostsPhotosFacade = usersPostsPhotosFacade;
            _commentsFacade = commentsFacade;
        }
        [HttpGet]
        public IActionResult Index(string username, int page)
        {
            // NOTE: the USERNAME is going to be given by ROUTE system!
            long userId = 0; // The user who is visiting the page
            if (User.Identity.IsAuthenticated) userId = (long)ClaimUtility.GetUserId(User as ClaimsPrincipal);
            ModelGetInformationByUsername modelGetInformationByUsername = new ModelGetInformationByUsername
            {
                UsernameOfThePage = username,
                ResultGetUsersInformationByUsernameServiceDto = _userInformationFacade.GetUsersInformationByUsernameService.Execute(new RequestUsersInformationByUsernameServiceDto
                {
                    Username = username
                }),
                ResultGetUsersInformationPhotosByUsernameServiceDto = _userInformationFacade.GetUsersInformationPhotosByUsernameService.Execute(new RequestGetUsersInformationPhotosByUsernameServiceDto
                {
                    Username = username,
                    TotalPhotos = 6,
                    UserId = userId,
                }),
                IsVisitorOwner = (_userInformationFacade.GetUsersInformationUsernameByUserIdService.Execute(new RequestGetUsersInformationUsernameByUserIdServiceDto
                {
                    UsersId = userId,
                }).Data == username) ? true : false,
                ResultGetUsersPostsServiceDto = _usersPost.GetUsersPostsService.Execute(new RequestGetUsersPostsServiceDto
                {
                    Username = username,
                    UserId = userId,
                    CurrentPage = page,
                }).Data,
            };
            return View(modelGetInformationByUsername);
        }
        [HttpGet]
        public IActionResult GetMorePost(string username, int page)
        {
            // NOTE: the USERNAME is going to be given by MODEL and the MODEL will be filled up when the page loads!
            long userId = 0; // The user who is visiting the page
            if (User.Identity.IsAuthenticated) userId = (long)ClaimUtility.GetUserId(User as ClaimsPrincipal);

            return Json(_usersPost.GetUsersPostsService.Execute(new RequestGetUsersPostsServiceDto
            {
                Username = username,
                UserId = userId,
                CurrentPage = page,
            }).Data);
        }
        [HttpGet]
        public IActionResult GetInfoAbout(string username)
        {
            return Json(_userInformationFacade.GetUsersInformationAboutByUsernameService.Execute(new RequestGetUsersInformationAboutByUsernameServiceDto
            {
                Username = username
            }));
        }
        [HttpGet]
        public IActionResult GetInfoPositions(string positions)
        {
            return Json(_userInformationFacade.GetUsersInformationPositionsService.Execute(new RequestGetUsersInformationPositionsServiceDto
            {
                Positions = positions,
            }));
        }
        [HttpGet]
        public IActionResult GetInfoContact(string username)
        {
            return Json(_userInformationFacade.GetUsersInformationContactByUsernameService.Execute(new RequestGetUsersInformationContactByUsernameServiceDto
            {
                Username = username
            }));
        }
        [HttpPost]
        public IActionResult PostComment(RequestPostCommentServiceDto req)
        {
            var userId = (long)ClaimUtility.GetUserId(User as ClaimsPrincipal);
            req.UsersId = userId;
            req.Email = ClaimUtility.GetUserEmail(User as ClaimsPrincipal);
            return Json(_commentsFacade.PostCommentService.Execute(req));
        }
        [HttpGet]
        public IActionResult GetCommentById(Guid Id)
        {
            long userId = 0;
            if (User.Identity.IsAuthenticated) userId = (long)ClaimUtility.GetUserId(User as ClaimsPrincipal);
            return Json(_commentsFacade.GetCommentsBySectionIdService.Execute(new RequestGetCommentsBySectionIdServiceDto
            {
                Section = 0,
                SectionId = Id,
                UserId = userId,
            }));
        }
        [HttpPost]
        public IActionResult DeleteComment(RequestDeleteCommentServiceDto req)
        {
            long userId = 0;
            if (User.Identity.IsAuthenticated) userId = (long)ClaimUtility.GetUserId(User as ClaimsPrincipal);
            req.UserId = userId;
            return Json(_commentsFacade.DeleteCommentService.Execute(req));
        }
        [HttpPost]
        public IActionResult PostPhotoIncrementVisitorCounter(RequestPostUsersPhotoIncreaseVisitorCounterServiceDto req)
        {
            return Json(_userPhoto.PostUsersPhotoIncreaseVisitorCounterService.Execute(req));
        }
        [HttpPost]
        public IActionResult PostLike(RequestPostLikeServiceDto req)
        {
            long userId = (long)ClaimUtility.GetUserId(User as ClaimsPrincipal);
            req.UsersId = userId;
            return Json(_ikesFacade.PostLikeService.Execute(req));
        }
        [HttpPost]
        public IActionResult PostPost(RequestPostUsersPostServiceDto req)
        {
            long userId = (long)ClaimUtility.GetUserId(User as ClaimsPrincipal);
            req.UsersId = userId;
            req.From = userId;
            return Json(_usersPost.PostUsersPostService.Execute(req));
        }
        [HttpPut]
        public IActionResult UpdatePostArchive(RequestUpdateUsersPostArchiveServiceDto req)
        {
            return Json(_usersPost.UpdateUsersPostArchiveService.Execute(req));
        }
        [HttpDelete]
        public IActionResult DeletePost(RequestDeleteUsersPostServiceDto req)
        {
            return Json(_usersPost.DeleteUsersPostService.Execute(req));
        }
    }
}

Endpoint.Site/Views/Shared/Components/UserPhotosNavigation/UserPhotosNavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Endpoint.Site.Views.Shared.Components.UserPhotosNavigation
{
    public class UserPhotosNavigationViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("Index");
        }
    }
}

Endpoint.Site/Views/User/Photos.cshtml
@* DevelopeR: Alimohammad Eghbaldar http://eghbaldar.ir *@
@using Endpoint.Site.Models.Users.GetPhoto
@using galaxypremiere.Application.Services.UsersPhotos.Queries.GetUsersPhotoAlbum;
@model dynamic
@{
    Layout = "~/Views/Shared/_LayoutInnerPages.cshtml";
}
@await Component.InvokeAsync("UserPhotosNavigation")

<div id="TabUserAlbums" class="TabcontentClass active">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">ALBUMS</h4>
        </div>
        <div class="card-body">
            <div class="basic-form">
                <!-- Gallery section -->
                <div class="col-md-12">
                    <div class="white_shd full margin_bottom_30">
                        <div class="row mt-3" id="divAlbum">
                            <div class="col-sm-4 col-md-3 margin_bottom_30 album">
                                <div class="column">
                                    <a data-fancybox="gallery"
                                       onclick="OpenModalAddAlbum();">
                                        <img class="img-responsive img-crop-square"
                                             src="~/SiteTemplate/innerpages/images/layout_img/addAlbumProfile.svg" alt="#">
                                    </a>
                                </div>
                                <div class="heading_section">
                                    <h4>+ ADD A NEW ALBUM</h4>
                                </div>
                            </div>
                            @*@foreach (GetUsersPhotoAlbumServiceDto album in Model.Album.resultGetUsersPhotoAlbumServiceDto){}*@
                            @for (int i = 0; i <= Model.Album.resultGetUsersPhotoAlbumServiceDto.Count - 1; i++)
                            {
                                <div class="col-sm-4 col-md-3 margin_bottom_30 album" id="divAlbum_@Model.Album.resultGetUsersPhotoAlbumServiceDto[i].Id">
                                    <div class="column">
                                        <a data-fancybox="gallery" onclick="OpenAlbum('@Model.Album.resultGetUsersPhotoAlbumServiceDto[i].Id')">
                                            @if (Model.Album.resultGetUsersPhotoAlbumServiceDto[i].RandomPhoto == null)
                                            {
                                                <img class="img-responsive img-crop-square albumCover_@Model.Album.resultGetUsersPhotoAlbumServiceDto[i].Id"
                                             src="~/SiteTemplate/innerpages/images/layout_img/addPhotoProfile.svg">
                                            }
                                            else
                                            {
                                                <img class="img-responsive img-crop-square albumCover_@Model.Album.resultGetUsersPhotoAlbumServiceDto[i].Id"
                                             src="~/SiteTemplate/innerpages/images/user-photos/@Model.Album.resultGetUsersPhotoAlbumServiceDto[i].RandomPhoto">
                                            }

                                        </a>
                                        <div class="divAlbumMenu">
                                            <div class="dropdown">
                                                <button class="dropbtn">
                                                    <i class="fa fa-ellipsis-v"></i>
                                                </button>
                                                <div class="dropdown-content">
                                                    <a onclick="OpenAlbum('@Model.Album.resultGetUsersPhotoAlbumServiceDto[i].Id')">Photos</a>
                                                    <a onclick="DeletePhotoAlbum('@Model.Album.resultGetUsersPhotoAlbumServiceDto[i].Id')">Delete</a>
                                                    <a onclick="UpdatePhotoAlbumTitle('@Model.Album.resultGetUsersPhotoAlbumServiceDto[i].Id')">Rename</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="heading_section">
                                        <h4>
                                            <span id="titleAlbumH4_@Model.Album.resultGetUsersPhotoAlbumServiceDto[i].Id">
                                                @Model.Album.resultGetUsersPhotoAlbumServiceDto[i].Title
                                                </span>
                                            </h4>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="TabUserPhotos" class="TabcontentClass">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title"><span id="spanAlbumName">Loading Album ...</span> <span class="splitter">| PHOTOS</span></h4>
        </div>
        <div class="card-body p-0">
            @*<div class="basic-form">*@

            <input type="hidden" id="hiddenAlbumId" />
            @*88888888888888888888888888888888888888888888*@
            <div id="dropzoneAvatar" class="dropped m-0">
                <div>
                    <img src="~/SiteTemplate/innerpages/images/user-headshot/" />
                </div>
                <div id="HeadshotLoader" class="loader"></div>
                <div id="HeadshotChangePhoto" class="HoverChangePhoto">CLICK OR DRAG TO UPLOAD</div>
                <input id="filedropzoneAvatar" type="file" />
            </div>
            @*88888888888888888888888888888888888888888888*@
            <!-- Gallery -->
            <div class="containerG p-2" id="containerPhotos">
                <div class="rowG">
                    @if (Model.Photo.resultGetUsersPhotoPhotosServiceDto != null)
                    {
                        @for (int i = 0; i <= Model.Photo.resultGetUsersPhotoPhotosServiceDto.Count - 1; i++)
                        {
                            <input type="hidden" id="hiddenPhotoDetail_@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Id" value="@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Detail" />
                            <input type="hidden" id="hiddenPhotoTitle_@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Id" value="@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Title" />
                            <div class="itemG @Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].UsersAlbumsId" hidden
                         id="photo_@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Id">
                                <a class="imgG" onclick="OpenModalPhoto('@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Id','@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Title','@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Detail','@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Filename')">
                                    <img src="~/SiteTemplate/innerpages/images/user-photos/@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Filename"
                                 class="rounded"
                                 alt="@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Title" />
                                </a>
                                <span class="caption" onclick="OpenModalPhoto('@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Id','@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Title','@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Detail','@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Filename')">
                                    <a>
                                        @if (Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Title == null)
                                        {
                                            <span id="spanTitle_@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Id">- unknown title -</span>
                                        }
                                        else
                                        {
                                            <span id="spanTitle_@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Id">@Model.Photo.resultGetUsersPhotoPhotosServiceDto[i].Title </span>
                                        }
                                    </a>
                                </span>

                            </div>
                        }
                    }
                </div>
            </div>
            <!-- Gallery -->
            @*</div>*@
        </div>
    </div>
</div>

<!-- Modal Photo -->
<div class="modal fade" id="modalPhoto">

    <input id="HiddenPhotoID" type="hidden" />

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">PHOTO DETAIL</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row ">
                        <div class="col-md text-center">
                            <img id="photo" class="rounded img-fluid" />
                            <div class="inputs p-2">
                                <div class="inputSwitch">
                                    <span class="spanInputSwitch fw-bold" id="txtPhotoTitleSpan"></span>
                                    <input id="txtPhotoTitle" class="form-control" hidden />
                                </div>
                                <div class="inputSwitch">
                                    <span class="spanInputSwitch" style=" white-space: pre-line;" id="txtPhotoDetailSpan"></span>
                                    <textarea id="txtPhotoDetail" class="form-control" cols="40" rows="5" hidden></textarea>
                                </div>
                            </div>

                            <hr />
                            <a href="#" class="sharedIcon fa fa-facebook"></a>
                            <a href="#" class="sharedIcon fa fa-linkedin"></a>
                            <a href="#" class="sharedIcon fa fa-twitter"></a>
                            <a href="#" class="sharedIcon fa fa-google"></a>
                            <a href="#" class="sharedIcon fa fa-instagram"></a>
                            <a href="#" class="sharedIcon fa fa-pinterest"></a>
                        </div>

                    </div>
                </div>
            </div>
            <div class="modal-footer">

                <div class="icon_info">
                    <div class="float-sm-end">
                        <button type="button"
                                onclick="DeletePhotoPhoto();" class="btn btn-secondary">
                            DELETE PHOTO
                        </button>
                    </div>
                    <ul>
                        <li><a href="#" class="fa fa-heart-o"><span class="badge">3</span></a></li>
                    </ul>
                    <ul>
                        <li><a href="#" class="fa fa-comments-o"><span class="badge">3</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

@section Styles{
    <link href="~/sitetemplate/innerpages/pagecssjs/user/photos/photos.css" rel="stylesheet" />
}

@section Scripts{
    @* Tabs *@
    <script src="~/sitetemplate/innerpages/plugins/tabNavigation/tab.js"></script>
    @* File Extension and Volume *@
    <script src="~/lib/kingfuncs/fileextensionsize/fileextensionsize.js"></script>
    @* Functions *@
    <script src="~/sitetemplate/innerpages/pagecssjs/user/photos/photos.js"></script>
}